# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13febc67859c0d04539dc6f1b52ce7322ab7d5bda22a6c94241f661ca691beb1d5da8a7b8f726d2c83d7c5e327d6f17e65b44a5a5c2dd660e3bd88dea1966f10

test:
  secret_key_base: 721d4d4438bb939e343b05b529417856225cd882f3c005f8bb878c763a600b638e7c788ff11a776c277c16aa769063b9117d195ea3bd235733aa90c0c6430b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
